export const columns = [
    { field: "id", headerName: "ID", width: 70 },
    { field: "persona", headerName: "Persona", width: 130 },
    { field: "apellidoP", headerName: "ApellidoP", width: 150 },
    { field: "apellidoM", headerName: "ApellidoM", width: 150 },
    { field: "nserie", headerName: "Numero de Serie", width: 150 },
    { field: "marca", headerName: "Marca", width: 70 },
    { field: "modelo", headerName: "Modelo", width: 100 },
    { field: "color", headerName: "Color", width: 100 },
    { field: "botones", headerName: "Acción", width: 150 },
  ];
  
  export const rows = [
    {
      id: 1,
      persona: "nombre1",
      apellidoP: "apellidoP1",
      apellidoM: "apellidoM1",
      nserie: "322423",
      marca: "HP",
      modelo: "HSDUF7",
      color: "Negro",
    },
    {
      id: 2,
      persona: "nombre2",
      apellidoP: "apellidoP2",
      apellidoM: "apellidoM2",
      nserie: "322423",
      marca: "HP",
      modelo: "HSDUF7",
      color: "Blanco",
    },
    {
      id: 3,
      persona: "nombre3",
      apellidoP: "apellidoP3",
      apellidoM: "apellidoM3",
      nserie: "322423",
      marca: "HP",
      modelo: "HSDUF7",
      color: "Negro",
    },
    {
      id: 4,
      persona: "nombre4",
      apellidoP: "apellidoP4",
      apellidoM: "apellidoM4",
      nserie: "322423",
      marca: "HP",
      modelo: "HSDUF7",
      color: "Azul",
    },
    {
      id: 5,
      persona: "nombre5",
      apellidoP: "apellidoP5",
      apellidoM: "apellidoM5",
      nserie: "322423",
      marca: "HP",
      modelo: "HSDUF7",
      color: "Rojo",
    },
    {
      id: 6,
      persona: "nombre6",
      apellidoP: "apellidoP6",
      apellidoM: "apellidoM6",
      nserie: "322423",
      marca: "HP",
      modelo: "HSDUF7",
      color: "Rojo",
    },
    {
      id: 7,
      persona: "nombre7",
      apellidoP: "apellidoP7",
      apellidoM: "apellidoM7",
      nserie: "322423",
      marca: "HP",
      modelo: "HSDUF7",
      color: "Morado",
    },
  ];