export const LIMPIAR_ALERTA = 'ALERTA'

export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const USUARIO_AUTENTICADO_ADMIN = 'USUARIO_AUTENTICADO_ADMIN'
export const USUARIO_AUTENTICADO_CLIENTE = 'USUARIO_AUTENTICADO_CLIENTE'
export const CERRAR_SESION = 'CERRAR_SESION'